version: '3.8'
services:
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017
      - 28017:28017
    command: --replSet rs0
  pubsub:
    image: redis
    ports:
      - '6379:6379'
    command: redis-server
