version: '3.8'
services:
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017
      - 28017:28017
    command: --replSet rs0

  # cache:
  #   image: redis
  #   ports:
  #     - '6379:6379'
  #   command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
